fix(agw): Fixed ENB Complete Reset Scenario
facebookexperimental/S1APTester pull request #81
Opened 2022-06-24 05:28 UTC by VinashakAnkitAman

## Title
fix(agw): Fixed ENB Complete Reset Scenario

## Summary
As per the Github issue https://github.com/magma/magma/issues/12583, the enb complete reset testcase was failing after the merge of PR #70. The testcase was getting stuck at the detach procedure waiting for detach accept indication and was failing with timeout. This PR fixes the issue with the enb complete reset scenario.

## Test plan
Verified with sanity and as individual test case

2022-06-24 06:05 UTC, pruthvihebbani requested changes

2022-06-24 06:05 UTC, pruthvihebbani commented on TestCntlrApp/src/enbApp/nb_s1ap_hndlr.c
> +   ret = cmAllocEvnt(sizeof(S1apPdu), NB_SZ_MEM_SDU_SIZE, &nbCb.mem,
ret is not used anywhere. You can directly check the return type of the fun against ROK/RFAILED -> 
if ((cmAllocEvnt)!=ROK)

2022-06-24 06:13 UTC, VinashakAnkitAman commented on TestCntlrApp/src/enbApp/nb.c
> +             resetMsgInfo.s1apIdCnt++;
For getting the count of UEs associated to this eNB. Based on this count, resetMsgInfo.enbUeS1apIdLst and resetMsgInfo.mmeUeS1apIdLst will be allocated of that size and then in the next loop these lists will be filled with UE Ids.

2022-06-24 06:25 UTC, pruthvihebbani commented on TestCntlrApp/src/enbApp/nb.c
> +             resetMsgInfo.s1apIdCnt++;
Can you add a brief description here

2022-06-30 11:10 UTC, pruthvihebbani approved these changes
lgtm

2022-07-01 07:46 UTC, rsarwad commented on TestCntlrApp/src/enbApp/nb_s1ap_hndlr.c
> +      NB_LOG_ERROR(&nbCb, "cmAllocEvnt failed");
On failing to create memory for resetReqPdu1, free memeory for resetReqPdu

2022-07-01 07:48 UTC, rsarwad commented on TestCntlrApp/src/enbApp/nb_s1ap_hndlr.c
> +   if(cmAllocEvnt(sizeof(S1apPdu), NB_SZ_MEM_SDU_SIZE, &nbCb.mem,
Check whether resetReqPdu1 is getting freed.

2022-07-01 07:49 UTC, rsarwad requested changes
Left few comments

2022-07-14 13:20 UTC, rsarwad approved these changes
LGTM

2022-07-14 13:21 UTC, merged